services:
  trainer-bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - STATUS_TOKEN=your-secret-token
      - DATA_SOURCE=coingecko
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1516867950706032691/jbkI3AtCR2LPIoLvEzSZkZOU5WpN5w28mJEqrm2tKpYYbTFyuEEQ3vVHl1fsQ0lE4TGJ
    restart: unless-stopped
