services:
  trainer-bot:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - STATUS_TOKEN=your-secret-token
      - DATA_SOURCE=coingecko
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1517392718488146020/DUU6wmDxpN8frACA2moHluDSageqctmANKsF6Hyd0kFGvw_XjI4oe2dnZo4VogYOUZJx
    restart: unless-stopped
